// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/27/2025, 9:14:06 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/mac/Desktop/AL-Tech/Q-A-Project/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Desktop/AL-Tech/Q-A-Project/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Desktop/AL-Tech/Q-A-Project/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Desktop/AL-Tech/Q-A-Project/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Desktop/AL-Tech/Q-A-Project/frontend/plugins/**/*.{js,ts,mjs}","/Users/mac/Desktop/AL-Tech/Q-A-Project/frontend/composables/**/*.{js,ts,mjs}","/Users/mac/Desktop/AL-Tech/Q-A-Project/frontend/utils/**/*.{js,ts,mjs}","/Users/mac/Desktop/AL-Tech/Q-A-Project/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Desktop/AL-Tech/Q-A-Project/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Desktop/AL-Tech/Q-A-Project/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;